// <auto-generated />
using IT3047CGroupProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3047CGroupProject.Migrations
{
    [DbContext(typeof(PhotographyContext))]
    partial class PhotographyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3047CGroupProject.Models.Camera", b =>
                {
                    b.Property<int>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CameraId"));

                    b.Property<string>("CameraBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CameraName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CameraPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CameraId");

                    b.ToTable("Cameras");

                    b.HasData(
                        new
                        {
                            CameraId = 1,
                            CameraBrand = "Canon",
                            CameraDescription = "A high-resolution full-frame mirrorless camera with advanced features.",
                            CameraModel = "EOS R5",
                            CameraName = "Canon EOS R5",
                            CameraPrice = 3899.00m
                        },
                        new
                        {
                            CameraId = 2,
                            CameraBrand = "Nikon",
                            CameraDescription = "A versatile full-frame mirrorless camera with excellent image quality.",
                            CameraModel = "Z7 II",
                            CameraName = "Nikon Z7 II",
                            CameraPrice = 2999.95m
                        },
                        new
                        {
                            CameraId = 3,
                            CameraBrand = "Sony",
                            CameraDescription = "A popular full-frame mirrorless camera known for its speed and performance.",
                            CameraModel = "Alpha a7 III",
                            CameraName = "Sony Alpha a7 III",
                            CameraPrice = 1998.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
